apiVersion: v1
kind: Service
metadata:
  labels:
    name: wordpress
  name: wordpress
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
  selector:
    app: wordpress
  type: NodePort
