apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ramnginx
  name: ramnginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ramnginx
  template:
    metadata:
      labels:
        app: ramnginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
